# base image
FROM continuumio/miniconda3:latest

# load in the environment.yml file
ADD ./docker/environment.yml /

RUN conda install -c conda-forge xgboost matplotlib jupyterlab nodejs
RUN conda install -c anaconda scikit-learn pandas numpy ipywidgets




# create the environmnt
RUN conda update -n base conda -y && conda env update

RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager
