name: base                                                                   
channels:                                                                    
  - defaults                                                                 
dependencies:   
  - pandas
  - numpy
  - xgboost
  - pandas-profiling
  - plotly
  - matplotlib
  - scikit-learn
  - jupyterlab
